name: TypeScript Type Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        working-directory: ./Dunnhumby.Web
        run: bun install

      - name: Run TypeScript Type Check
        working-directory: ./Dunnhumby.Web
        run: bun run tsc
